// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCity.Infrastructure.Persistence;

#nullable disable

namespace SmartCity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartCityDbContext))]
    partial class SmartCityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCity.Domain.Entities.FireStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("fire_stations", (string)null);
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("hospitals", (string)null);
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("OccurredAt");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.LocationAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("FinalNeedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("FireStationDistanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("HospitalDistanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("IncidentDensityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PopulationScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoadAccessibilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "CreatedAt");

                    b.ToTable("location_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_location_analyses_scores", "\"HospitalDistanceScore\" BETWEEN 0 AND 100 AND \"FireStationDistanceScore\" BETWEEN 0 AND 100 AND \"RoadAccessibilityScore\" BETWEEN 0 AND 100 AND \"PopulationScore\" BETWEEN 0 AND 100 AND \"IncidentDensityScore\" BETWEEN 0 AND 100 AND \"FinalNeedScore\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<double>("PopulationDensity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("regions", null, t =>
                        {
                            t.HasCheckConstraint("ck_regions_incident_count", "\"IncidentCount\" >= 0");

                            t.HasCheckConstraint("ck_regions_population", "\"Population\" >= 0");

                            t.HasCheckConstraint("ck_regions_population_density", "\"PopulationDensity\" >= 0");
                        });
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.Road", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(LineString,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("RoadType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("roads", (string)null);
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.LocationAnalysis", b =>
                {
                    b.HasOne("SmartCity.Domain.Entities.Region", "Region")
                        .WithMany("LocationAnalyses")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SmartCity.Domain.Entities.Region", b =>
                {
                    b.Navigation("LocationAnalyses");
                });
#pragma warning restore 612, 618
        }
    }
}
